default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: nimbu
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: contact_search_development

production:
  <<: *default
  adapter: postgresql
  database: contact_search_production
  username: root
  password: nimbu